/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Entidades.ControladorEntidades;
import Persistencia.ClientesJpaController;
import java.awt.Color;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class RegistroLicencia extends javax.swing.JFrame {

    ControladorEntidades control = new ControladorEntidades();
    Date date = new Date();
    ClientesJpaController cliJpa = new ClientesJpaController();

    /**
     * Creates new form RegistroLicencia
     */
    public RegistroLicencia() {
        initComponents();
        btnRegistrar.setEnabled(false);

    }

    /**
     * Metodo para validar datos en blanco
     *
     * @return
     */
    private boolean validarDatos() {
        if (txtNombre.getText().isEmpty()
                || txtApellidoM.getText().isEmpty()
                || txtApellidoP.getText().isEmpty()
                //                || txtRFC.getText().isEmpty()
                || txtTelefono.getText().isEmpty()) {

            return true;
        } else {
            return false;
        }
    }

    public boolean validarFormatoRfc(String str) {
        String pattern = "\\w{13}";

        Pattern regex = Pattern.compile(pattern);
        Matcher matcher = regex.matcher(str);
        if (matcher.matches()) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Metodo para validar Cadenas
     *
     * @param input
     * @return
     */
    public boolean validarCadenas(String input) {
        if (input.matches("^[a-zA-Z ]*$")) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Metodo para validar Numeros mediante expresiones regulares
     *
     * @param datos cadena a validar
     * @return boolean true o false dependiendo la validez
     */
    public static boolean validarNumeros(String datos) {
        return datos.matches("[0-9]");

    }

    /**
     * Metodo para validar Letras mediante expresiones regulares
     *
     * @param dato cadena a validar
     * @return
     */
    public boolean validarSoloLetras(String dato) {
        return dato.matches("[a-zA-Z]*");
    }

    /**
     * Metodo para validar Telefono mediante expresiones regulares
     *
     * @param telefono el Telefono del Cliente
     * @return valor boolean dependiente de la validez
     */
    public boolean validarTelefono(String telefono) {

        String pattern = "\\d{10}";
        Pattern regex = Pattern.compile(pattern);
        Matcher matcher = regex.matcher(telefono);
        if (matcher.matches()) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cmbDiscapacitado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbVigencia = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtFechaVigencia = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFechaExpedicion = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtPrecio1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtRFC = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFechaNac2 = new com.toedter.calendar.JDateChooser();
        labelErrorNombre = new javax.swing.JLabel();
        labelErrorApellido = new javax.swing.JLabel();
        labelErrorApellidoMat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(189, 74, 54));
        jLabel8.setText("Discapacitado:");

        cmbDiscapacitado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbDiscapacitado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Si", "No" }));
        cmbDiscapacitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDiscapacitadoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(189, 74, 54));
        jLabel9.setText("Fecha Vigencia:");

        cmbVigencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbVigencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3" }));
        cmbVigencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbVigenciaMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(189, 74, 54));
        jLabel10.setText("Precio de Licencia:");

        txtFechaVigencia.setEnabled(true);
        txtFechaVigencia.setEnabled(false);
        txtFechaVigencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(189, 74, 54));
        jLabel11.setText("Fecha Expedición:");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(189, 74, 54));
        jLabel1.setText("Registro al Sistema de Licencia");

        Date fecha = new Date();
        txtFechaExpedicion.setDate(fecha);
        txtFechaExpedicion.setEnabled(false);
        txtFechaExpedicion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(189, 74, 54));
        jLabel2.setText("RFC: ");

        txtPrecio1.setEditable(false);
        txtPrecio1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPrecio1.setForeground(new java.awt.Color(189, 74, 54));
        txtPrecio1.setText("0.0");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(189, 74, 54));
        jLabel3.setText("Nombre: ");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(189, 74, 54));
        jButton1.setText("Aceptar Datos");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(189, 74, 54));
        jLabel4.setText("Fecha Nacimiento: ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(189, 74, 54));
        jLabel12.setText("Años:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(189, 74, 54));
        jLabel5.setText("Telefono: ");

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(189, 74, 54));
        txtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtRFC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRFC.setForeground(new java.awt.Color(189, 74, 54));
        txtRFC.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(189, 74, 54));
        txtTelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidoP.setForeground(new java.awt.Color(189, 74, 54));
        txtApellidoP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidoM.setForeground(new java.awt.Color(189, 74, 54));
        txtApellidoM.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(189, 74, 54));
        jLabel6.setText("Apellido Paterno:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(189, 74, 54));
        jLabel7.setText("Apellido Materno:");

        txtFechaNac2.setForeground(new java.awt.Color(189, 74, 54));
        txtFechaNac2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(6, 6, 6)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTelefono)
                                            .addComponent(txtFechaNac2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelErrorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelErrorApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelErrorApellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(cmbDiscapacitado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(cmbVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtFechaExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtFechaVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(162, 162, 162)
                                        .addComponent(jLabel12))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addComponent(btnCancelar)
                                .addGap(28, 28, 28)
                                .addComponent(btnRegistrar)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbDiscapacitado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFechaExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(labelErrorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(labelErrorApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addComponent(labelErrorApellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFechaVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtFechaNac2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        new TramiteLicencia().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        String precioValidacion = txtPrecio1.getText();

        if (precioValidacion.equalsIgnoreCase("0.0")) {
            JOptionPane.showMessageDialog(null,
                    "Revise su selección de discapacidad y/o vigencia",
                    "Error de información",
                    JOptionPane.ERROR_MESSAGE);

            btnRegistrar.setEnabled(false);
        } else if (validarFormatoRfc(this.txtRFC.getText()) == false) {
            JOptionPane.showMessageDialog(null, "El RFC debe contener 13 dígitos.");
            txtRFC.setBackground(Color.YELLOW);
        } else if (validarTelefono(this.txtTelefono.getText()) == false) {

            JOptionPane.showMessageDialog(null, "Los datos son incorrectos en el teléfono ");
            txtTelefono.setBackground(Color.YELLOW);

        } else if (txtTelefono.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "El teléfono debe contener 10 dígitos");
            txtTelefono.setBackground(Color.YELLOW);
        } else if (validarCadenas(this.txtNombre.getText()) == false) {
            txtTelefono.setBackground(Color.WHITE);
            JOptionPane.showMessageDialog(null, "Los datos son incorrectos en el nombre ");
            txtNombre.setBackground(Color.YELLOW);

        } else if (validarCadenas(this.txtApellidoP.getText().trim()) == false) {
            txtNombre.setBackground(Color.WHITE);
            JOptionPane.showMessageDialog(null, "No se aceptan valores numericos en el apellido paterno ");
            txtApellidoP.setBackground(Color.YELLOW);

        } else if (validarCadenas(this.txtApellidoM.getText().trim()) == false) {
            txtApellidoP.setBackground(Color.WHITE);
            JOptionPane.showMessageDialog(null, "No se aceptan valores numericos en el apellido materno ");
            txtApellidoM.setBackground(Color.YELLOW);
        } else if (control.validarClienteExistente(this.txtRFC.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Ya hay un usuario con este RFC");
            txtRFC.setBackground(Color.YELLOW);
        } else if (validarCadenas(this.txtApellidoM.getText().trim()) == true
                && validarCadenas(this.txtApellidoP.getText().trim()) == true
                && validarCadenas(this.txtNombre.getText()) == true
                && validarTelefono(this.txtTelefono.getText()) == true) {

            String RFC = txtRFC.getText().toUpperCase();
            String nombre = txtNombre.getText();
            String apellidoP = txtApellidoP.getText();
            String apellidoM = txtApellidoM.getText();
            Date fechaNacimiento = txtFechaNac2.getDate();
            String numTelefono = txtTelefono.getText();

            String discapacitado = (String) cmbDiscapacitado.getSelectedItem();
            Date fechaExp = txtFechaExpedicion.getDate();
            Date fechaVig = txtFechaVigencia.getDate();
            String anios = (String) cmbVigencia.getSelectedItem();
            String precio = txtPrecio1.getText();

            control.guardarCliente(RFC, nombre, apellidoP, apellidoM, fechaNacimiento, numTelefono, discapacitado, fechaExp, fechaVig, anios, precio);
            control.guardarEnHistorial("Licencia", precio, date, RFC);

            JOptionPane optionPane = new JOptionPane("Se guardó correctamente la infomación");
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog = optionPane.createDialog("Guardado exitoso");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);

            txtRFC.setText("");
            txtNombre.setText("");
            txtApellidoP.setText("");
            txtApellidoM.setText("");
            txtFechaNac2.setDate(null);
            txtTelefono.setText("");
            cmbDiscapacitado.setSelectedIndex(0);
            txtFechaExpedicion.setDate(null);
            txtFechaVigencia.setDate(null);
            cmbVigencia.setSelectedIndex(0);

            this.setVisible(false);
            new TramiteLicencia().setVisible(true);
        }


    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cmbDiscapacitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDiscapacitadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDiscapacitadoActionPerformed

    private void cmbVigenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbVigenciaMouseClicked


    }//GEN-LAST:event_cmbVigenciaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (validarDatos() == true) {
            JOptionPane.showMessageDialog(null,
                    "Hay uno o más campos vacíos",
                    "Error de información",
                    JOptionPane.ERROR_MESSAGE);

        } else if (validarFormatoRfc(this.txtRFC.getText()) == false) {
            JOptionPane.showMessageDialog(null, "El RFC debe contener 13 dígitos");
            txtRFC.setBackground(Color.YELLOW);
        } else if (validarTelefono(this.txtTelefono.getText()) == false) {

            JOptionPane.showMessageDialog(null, "Los datos son incorrectos en el teléfono ");
            txtTelefono.setBackground(Color.YELLOW);
            txtRFC.setBackground(Color.WHITE);
        } else if (validarCadenas(this.txtNombre.getText()) == false) {
            txtTelefono.setBackground(Color.WHITE);
            JOptionPane.showMessageDialog(null, "Los datos son incorrectos en el nombre ");
            txtNombre.setBackground(Color.YELLOW);

        } else if (validarSoloLetras(this.txtApellidoP.getText().trim()) == false) {
            txtNombre.setBackground(Color.WHITE);
            JOptionPane.showMessageDialog(null, "No se aceptan valores numericos en el apellido paterno ");
            txtApellidoP.setBackground(Color.YELLOW);

        } else if (validarSoloLetras(this.txtApellidoM.getText().trim()) == false) {
            txtApellidoP.setBackground(Color.WHITE);
            JOptionPane.showMessageDialog(null, "No se aceptan valores numericos en el apellido materno ");
            txtApellidoM.setBackground(Color.YELLOW);
        } else if (txtTelefono.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "El teléfono debe contener 10 dígitos");
            txtTelefono.setBackground(Color.YELLOW);
        } else {
            int discapacitado = cmbDiscapacitado.getSelectedIndex();
            int vigencia = cmbVigencia.getSelectedIndex();

            if ((discapacitado == 1) && (vigencia == 1)) {
                txtPrecio1.setText("$200");

                Date fecha = this.txtFechaExpedicion.getDate();

                fecha.setYear(fecha.getYear() + 1);

                this.txtFechaVigencia.setDate(fecha);
            }

            if ((discapacitado == 1) && (vigencia == 2)) {
                txtPrecio1.setText("$500");
                Date fecha = this.txtFechaExpedicion.getDate();

                fecha.setYear(fecha.getYear() + 2);

                this.txtFechaVigencia.setDate(fecha);
            }

            if ((discapacitado == 1) && (vigencia == 3)) {
                txtPrecio1.setText("$700");
                Date fecha = this.txtFechaExpedicion.getDate();

                fecha.setYear(fecha.getYear() + 3);

                this.txtFechaVigencia.setDate(fecha);
            }

            if ((discapacitado == 2) && (vigencia == 1)) {
                txtPrecio1.setText("$600");
                Date fecha = this.txtFechaExpedicion.getDate();

                fecha.setYear(fecha.getYear() + 1);

                this.txtFechaVigencia.setDate(fecha);
            }

            if ((discapacitado == 2) && (vigencia == 2)) {
                txtPrecio1.setText("$900");
                Date fecha = this.txtFechaExpedicion.getDate();

                fecha.setYear(fecha.getYear() + 2);

                this.txtFechaVigencia.setDate(fecha);
            }

            if ((discapacitado == 2) && (vigencia == 3)) {
                txtPrecio1.setText("$1,100");
                Date fecha = this.txtFechaExpedicion.getDate();

                fecha.setYear(fecha.getYear() + 3);

                this.txtFechaVigencia.setDate(fecha);
            }

            this.btnRegistrar.setEnabled(true);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbDiscapacitado;
    private javax.swing.JComboBox<String> cmbVigencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelErrorApellido;
    private javax.swing.JLabel labelErrorApellidoMat;
    private javax.swing.JLabel labelErrorNombre;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private com.toedter.calendar.JDateChooser txtFechaExpedicion;
    private com.toedter.calendar.JDateChooser txtFechaNac2;
    private com.toedter.calendar.JDateChooser txtFechaVigencia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio1;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

//    public String generaRfc(){
//        String rfc = this.txtApellidoP.getText().substring(0, 2)+
//                this.txtApellidoM.getText().charAt(0)+
//                this.txtNombre.getText().charAt(0)+
//                this.txtFechaNac2.getDate().toString().substring(26, 28)+
//                this.txtFechaNac2.getDate().getMonth()+
//                this.txtFechaNac2.getDate().toString().substring(8, 10)+
//                "1HO";
//       
//        return rfc.toUpperCase();
//    }
}
